name: Run Python Scripts Automatically in Bangkok
on:
  schedule:
    # 每日台灣時間13:00
    - cron: '0 22 * * *'  # 注意: GitHub Actions 使用 UTC 時間，台灣時間早上6點相當於 UTC 22:00

jobs:
  run-scripts:
    runs-on: windows-latest  # 使用 Windows 環境

    strategy:
      max-parallel: 2  # 一次最多執行兩個腳本
      matrix:
        script:
          - 'Bangkok.py'
          - 'Bangkok_business.py'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4  # 確保使用最新版本

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium requests
                    
    - name: Chocolatey Action
      uses: crazy-max/ghaction-chocolatey@v3.2.0

    - name: Download ChromeDriver
      run: |
        choco install chromedriver --version=114.0.5735.90 -y  # 使用 Chocolatey 安裝 ChromeDriver
        # 確保將 <desired_version> 替換為所需的 ChromeDriver 版本      

    - name: Run script
      run: |
        python ${{ matrix.script }}  # 動態運行 Python 腳本
        y

    - name: Upload CSV as artifacts
      uses: actions/upload-artifact@v3  # 使用最新版本
      with:
        name: flight-data
        path: data/*.csv  # 上傳所有生成的 CSV 文件
